// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOGJx-YK65K4YUSaraVpfsFqfvuv4wcQ',
    appId: '1:523483187443:web:7ca0287f3c19618a194f86',
    messagingSenderId: '523483187443',
    projectId: 'ema-iron-tracker',
    authDomain: 'ema-iron-tracker.firebaseapp.com',
    storageBucket: 'ema-iron-tracker.appspot.com',
    measurementId: 'G-S0T05GBZE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0YitF5xH0PxMwZCnGNNO22lK5bEVYm8k',
    appId: '1:523483187443:android:f45db5ce415fb1d5194f86',
    messagingSenderId: '523483187443',
    projectId: 'ema-iron-tracker',
    storageBucket: 'ema-iron-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUAkVbyCqM4RXOBwHLrewmRA6cn2NMKtY',
    appId: '1:523483187443:ios:17075bc5f46860cd194f86',
    messagingSenderId: '523483187443',
    projectId: 'ema-iron-tracker',
    storageBucket: 'ema-iron-tracker.appspot.com',
    iosBundleId: 'com.example.irontracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUAkVbyCqM4RXOBwHLrewmRA6cn2NMKtY',
    appId: '1:523483187443:ios:17075bc5f46860cd194f86',
    messagingSenderId: '523483187443',
    projectId: 'ema-iron-tracker',
    storageBucket: 'ema-iron-tracker.appspot.com',
    iosBundleId: 'com.example.irontracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzOGJx-YK65K4YUSaraVpfsFqfvuv4wcQ',
    appId: '1:523483187443:web:f40c91390bbae32a194f86',
    messagingSenderId: '523483187443',
    projectId: 'ema-iron-tracker',
    authDomain: 'ema-iron-tracker.firebaseapp.com',
    storageBucket: 'ema-iron-tracker.appspot.com',
    measurementId: 'G-5SVKHVWETY',
  );

}